export const STEPS = ['Setup', 'Trigger Rules', 'Designer', 'Promo Code', 'Review'];

export const TYPES = [
  { id: 'exit_intent', label: 'Exit Intent Popup', icon: '🚪' },
  { id: 'time_delay', label: 'Time Delay Popup', icon: '⏱' },
  { id: 'scroll_depth', label: 'Scroll Depth Popup', icon: '📜' },
  { id: 'welcome_mat', label: 'Welcome Mat (full-screen)', icon: '🛋' },
  { id: 'upsell_modal', label: 'Upsell / Cross-sell Modal', icon: '🛒' },
  { id: 'promo_banner', label: 'Promo Code Banner', icon: '🏷' },
  { id: 'spin_wheel', label: 'Spin-to-Win Wheel', icon: '🎡' },
  { id: 'sticky_footer', label: 'Sticky Footer Bar', icon: '📌' },
];

export const defaultTrigger = {
  sensitivity: 'medium',
  timeDelaySeconds: 5,
  scrollDepthPercent: 50,
  pageTargeting: 'all',
  customUrlRegex: '',
  deviceDesktop: true,
  deviceMobile: true,
  deviceTablet: true,
  frequencyCap: 'once_per_session',
  cartValueFilter: false,
  cartValueMin: 0,
  scrollShortPageBehavior: 'immediate',
  scrollEvaluateOnLoad: true,
  welcomeMatDelayMs: 0,
  welcomeMatBackdropDismiss: true,
  upsellAfterAddDelayMs: 500,
  upsellSkuAllowlist: '',
  persistentBarDelayMs: 0,
  spinWheelTrigger: 'time_delay',
};

export const defaultDesign = {
  background: '#ffffff',
  backgroundOpacity: 0.95,
  size: 'medium',
  position: 'center',
  headline: 'Welcome!',
  headlineSize: 24,
  headlineBold: true,
  headlineColor: '#1f2937',
  subheadline: '',
  subheadlineSize: 16,
  subheadlineColor: '#6b7280',
  body: 'Get 10% off your first order.',
  bodySize: 14,
  bodyColor: '#4b5563',
  ctaText: 'Get Offer',
  ctaAction: 'copy_promo',
  ctaUrl: '',
  ctaBgColor: '#224BBD',
  ctaTextColor: '#ffffff',
  ctaBorderRadius: 8,
  secondaryCtaText: 'No thanks',
  imageDataUrl: '',
  showCloseButton: true,
  closeDelay: 0,
  animation: 'fade',
  exitTwoStep: true,
  exitGateHeadline: 'Wait — before you go…',
  exitGateSubheadline: 'You’re about to leave empty-handed',
  exitGateBody:
    'Are you sure? We’ve reserved an exclusive discount if you stay and complete your order.',
  exitStayCtaText: 'Yes, show me the offer',
  exitLeaveCtaText: 'No thanks, exit',
  exitGateStayBgColor: '#224BBD',
  exitGateStayTextColor: '#ffffff',
  exitGateLeaveColor: '#6b7280',
  exitOfferEyebrow: 'Special offer',
  exitOfferEyebrowColor: '#224BBD',
  welcomeMatInnerMaxPx: 640,
  barEdge: 'top',
  showPromoInBar: true,
  spinSegments: [
    { label: '10% off', weight: 1, code: '' },
    { label: 'Free shipping', weight: 1, code: '' },
    { label: 'Bonus offer', weight: 1, code: '' },
    { label: 'Try again', weight: 1, code: '' },
  ],
  spinRequireEmail: false,
  spinTitle: 'Spin to win!',
  spinSubtitle: 'Enter your email, then spin for an exclusive reward.',
  spinButtonLabel: 'Spin the wheel',
};

export const defaultPromo = {
  code: '',
  autoCopy: false,
  injectIntoCartUrl: false,
  expiryDate: '',
};
